package demoswing2;

import static demoswing2.AmbulancePage.data;
import static demoswing2.PlumberPage.data;
import javax.swing.JOptionPane;
import demoswing2.ServiceProviders;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author vp362
 */
public class ElectricianPage extends javax.swing.JFrame {

    String login_id, passwor_d;

    /**
     * Creates new form AmbulancePage
     */
    public ElectricianPage(String loginid, String password) {
        this.login_id = loginid;
        this.passwor_d = password;
        initComponents();
    }
    String CustName, CustContactno, CustAddress;
    Connection con = Database.getconnection();

    String ss_FullName = "", serviceType, s_contact, s_emaill, s_addresssing, s_city, s_state, s_pincode, s_fee, c_Fullname, c_contact, c_addressing;
//    String login_id, passwor_d;
    static ServiceProviderData[] data = new ServiceProviderData[5];

    static {
        data[0] = new ServiceProviderData("Umesh", "Chouhan", "400", "Male", "umesh1@gmail.com", "Electrician", "7777444420", "Scheme no. 94 World cup", "Indore", "Madhya Pradesh", "India", "452010", "Umesh@123");
        data[1] = new ServiceProviderData("Suresh", "Choudhary", "500", "Male", "suresh12@gmail.com", "Electrician", "6893547442", "25 ,Khandwa Naka ", "Sanawad", "Madhya Pradesh", "India", "452001", "Suresh@2611");

        data[2] = new ServiceProviderData("Johny", "Yadav", "600", "Male", "johny2@gmail.com", "Electrician", "8495621037", "Dwarkapuri Nagar", "Khandwa", "Madhya Pradesh", "India", "452010", "Johny@123");

        data[3] = new ServiceProviderData("Ramesh", "Sen", "800", "Male", "ramesh12@gmail.com", "Electrician", "6874591023", "12, Shyam Nagar", "Ujjain", "Madhya Pradesh", "India", "452010", "Ramesh@123");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jButton13 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jButton12 = new javax.swing.JButton();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jButton18 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel68 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        jLabel70 = new javax.swing.JLabel();
        jLabel71 = new javax.swing.JLabel();
        jLabel72 = new javax.swing.JLabel();
        jLabel73 = new javax.swing.JLabel();
        jLabel74 = new javax.swing.JLabel();
        jLabel75 = new javax.swing.JLabel();
        jLabel76 = new javax.swing.JLabel();
        jLabel77 = new javax.swing.JLabel();
        jLabel78 = new javax.swing.JLabel();
        jLabel79 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setForeground(new java.awt.Color(51, 51, 51));

        jLabel2.setBackground(new java.awt.Color(51, 51, 51));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel2.setText("Electrician  Services  Booking Page");

        jPanel3.setBackground(new java.awt.Color(0, 255, 255));

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 51, 51));
        jButton1.setText("Book Now");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(0, 102, 102));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 51));
        jLabel1.setText("Full Name");

        jLabel3.setBackground(new java.awt.Color(0, 102, 102));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 51));
        jLabel3.setText("Umesh Chouhan");

        jLabel4.setBackground(new java.awt.Color(0, 102, 102));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 51));
        jLabel4.setText("Contact no. :-");

        jLabel5.setBackground(new java.awt.Color(0, 102, 102));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 51, 51));
        jLabel5.setText("7777444420");

        jLabel6.setBackground(new java.awt.Color(0, 102, 102));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 51, 51));
        jLabel6.setText("Address :-");

        jLabel7.setBackground(new java.awt.Color(0, 102, 102));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 51, 51));
        jLabel7.setText("Sch no. 94 ,World -Cup Square");

        jLabel8.setBackground(new java.awt.Color(0, 102, 102));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 51, 51));
        jLabel8.setText("City :- ");

        jLabel9.setBackground(new java.awt.Color(0, 102, 102));
        jLabel9.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 51, 51));
        jLabel9.setText("Indore");

        jLabel10.setBackground(new java.awt.Color(0, 102, 102));
        jLabel10.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 51, 51));
        jLabel10.setText("State :-");

        jLabel11.setBackground(new java.awt.Color(0, 102, 102));
        jLabel11.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 51, 51));
        jLabel11.setText("Madhya Pradesh");

        jButton9.setBackground(new java.awt.Color(51, 51, 0));
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/demoswing2/Elec1.jpg"))); // NOI18N
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jLabel22.setBackground(new java.awt.Color(0, 102, 102));
        jLabel22.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(204, 204, 255));
        jLabel22.setText("Fee :-");

        jLabel23.setBackground(new java.awt.Color(0, 102, 102));
        jLabel23.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 51, 51));
        jLabel23.setText("400.0 Rs ");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel10)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel4))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel11)
                                            .addComponent(jLabel23)))))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(106, 106, 106)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel22)))
                        .addGap(0, 18, Short.MAX_VALUE))
                    .addComponent(jButton9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(jLabel23))
                .addGap(9, 9, 9)
                .addComponent(jButton1))
        );

        jPanel8.setBackground(new java.awt.Color(0, 204, 204));

        jButton13.setBackground(new java.awt.Color(51, 51, 0));
        jButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/demoswing2/Elec22.png"))); // NOI18N
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 51, 51));
        jButton2.setText("Book Now");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel56.setBackground(new java.awt.Color(0, 102, 102));
        jLabel56.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel56.setForeground(new java.awt.Color(0, 51, 51));
        jLabel56.setText("Full Name");

        jLabel57.setBackground(new java.awt.Color(0, 102, 102));
        jLabel57.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel57.setForeground(new java.awt.Color(0, 51, 51));
        jLabel57.setText("Suresh Choudhary");

        jLabel58.setBackground(new java.awt.Color(0, 102, 102));
        jLabel58.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel58.setForeground(new java.awt.Color(0, 51, 51));
        jLabel58.setText("Contact no. :-");

        jLabel59.setBackground(new java.awt.Color(0, 102, 102));
        jLabel59.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel59.setForeground(new java.awt.Color(0, 51, 51));
        jLabel59.setText("6893547442");

        jLabel60.setBackground(new java.awt.Color(0, 102, 102));
        jLabel60.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel60.setForeground(new java.awt.Color(0, 51, 51));
        jLabel60.setText("Address :-");

        jLabel61.setBackground(new java.awt.Color(0, 102, 102));
        jLabel61.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel61.setForeground(new java.awt.Color(0, 51, 51));
        jLabel61.setText("25, Khandwa Naka");

        jLabel62.setBackground(new java.awt.Color(0, 102, 102));
        jLabel62.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel62.setForeground(new java.awt.Color(0, 51, 51));
        jLabel62.setText("City :- ");

        jLabel63.setBackground(new java.awt.Color(0, 102, 102));
        jLabel63.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel63.setForeground(new java.awt.Color(0, 51, 51));
        jLabel63.setText("Sanawad");

        jLabel64.setBackground(new java.awt.Color(0, 102, 102));
        jLabel64.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel64.setForeground(new java.awt.Color(0, 51, 51));
        jLabel64.setText("State :-");

        jLabel65.setBackground(new java.awt.Color(0, 102, 102));
        jLabel65.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel65.setForeground(new java.awt.Color(0, 51, 51));
        jLabel65.setText("Madhya Pradesh");

        jLabel66.setBackground(new java.awt.Color(0, 102, 102));
        jLabel66.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel66.setForeground(new java.awt.Color(255, 51, 51));
        jLabel66.setText("Fee :-");

        jLabel67.setBackground(new java.awt.Color(0, 102, 102));
        jLabel67.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel67.setForeground(new java.awt.Color(0, 51, 51));
        jLabel67.setText("500.0 Rs ");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel56)
                                    .addComponent(jLabel58))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel8Layout.createSequentialGroup()
                                        .addComponent(jLabel59)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(jLabel57, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel60)
                                    .addComponent(jLabel62)
                                    .addComponent(jLabel64))
                                .addGap(41, 41, 41)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel63)
                                    .addComponent(jLabel61)
                                    .addComponent(jLabel65)
                                    .addComponent(jLabel67))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel66))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGap(106, 106, 106)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 70, Short.MAX_VALUE))
                    .addComponent(jButton13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel57)
                    .addComponent(jLabel56, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel58)
                    .addComponent(jLabel59))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel60)
                    .addComponent(jLabel61))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel62)
                    .addComponent(jLabel63))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel64)
                    .addComponent(jLabel65))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel66)
                    .addComponent(jLabel67))
                .addGap(9, 9, 9)
                .addComponent(jButton2))
        );

        jPanel5.setBackground(new java.awt.Color(255, 204, 204));

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 51, 51));
        jButton3.setText("Book Now");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel24.setBackground(new java.awt.Color(0, 102, 102));
        jLabel24.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 51, 51));
        jLabel24.setText("Driver Name :- ");

        jLabel25.setBackground(new java.awt.Color(0, 102, 102));
        jLabel25.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 51, 51));
        jLabel25.setText("Johny Yadav");

        jLabel26.setBackground(new java.awt.Color(0, 102, 102));
        jLabel26.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(0, 51, 51));
        jLabel26.setText("Contact no. :-");

        jLabel27.setBackground(new java.awt.Color(0, 102, 102));
        jLabel27.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(0, 51, 51));
        jLabel27.setText("8495621037");

        jLabel28.setBackground(new java.awt.Color(0, 102, 102));
        jLabel28.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(0, 51, 51));
        jLabel28.setText("Address :-");

        jLabel29.setBackground(new java.awt.Color(0, 102, 102));
        jLabel29.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(0, 51, 51));
        jLabel29.setText("Dwarkapuri Nagar");

        jLabel30.setBackground(new java.awt.Color(0, 102, 102));
        jLabel30.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(0, 51, 51));
        jLabel30.setText("City :- ");

        jLabel31.setBackground(new java.awt.Color(0, 102, 102));
        jLabel31.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(0, 51, 51));
        jLabel31.setText("Khandwa");

        jLabel52.setBackground(new java.awt.Color(0, 102, 102));
        jLabel52.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel52.setForeground(new java.awt.Color(0, 51, 51));
        jLabel52.setText("State :-");

        jLabel53.setBackground(new java.awt.Color(0, 102, 102));
        jLabel53.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel53.setForeground(new java.awt.Color(0, 51, 51));
        jLabel53.setText("Madhya Pradesh");

        jButton12.setBackground(new java.awt.Color(51, 51, 0));
        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/demoswing2/Elec3.jpg"))); // NOI18N
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jLabel54.setBackground(new java.awt.Color(0, 102, 102));
        jLabel54.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel54.setForeground(new java.awt.Color(255, 51, 51));
        jLabel54.setText("Fee :-");

        jLabel55.setBackground(new java.awt.Color(0, 102, 102));
        jLabel55.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel55.setForeground(new java.awt.Color(0, 51, 51));
        jLabel55.setText("600.0 Rs ");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel28)
                                    .addComponent(jLabel30)
                                    .addComponent(jLabel52))
                                .addGap(55, 55, 55)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel31)
                                    .addComponent(jLabel29)
                                    .addComponent(jLabel53)
                                    .addComponent(jLabel55))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel24)
                                    .addComponent(jLabel26))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(jLabel27)
                                        .addGap(0, 0, Short.MAX_VALUE))))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(106, 106, 106)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel54)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jButton12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel25)
                    .addComponent(jLabel24, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(jLabel27))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(jLabel29))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(jLabel31))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel52)
                    .addComponent(jLabel53))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel54)
                    .addComponent(jLabel55))
                .addGap(9, 9, 9)
                .addComponent(jButton3))
        );

        jPanel9.setBackground(new java.awt.Color(0, 255, 204));

        jButton18.setBackground(new java.awt.Color(51, 51, 0));
        jButton18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/demoswing2/Elec44.png"))); // NOI18N
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(0, 0, 0));
        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 51, 51));
        jButton4.setText("Book Now");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel68.setBackground(new java.awt.Color(0, 102, 102));
        jLabel68.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel68.setForeground(new java.awt.Color(0, 51, 51));
        jLabel68.setText("Driver Name :- ");

        jLabel69.setBackground(new java.awt.Color(0, 102, 102));
        jLabel69.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel69.setForeground(new java.awt.Color(0, 51, 51));
        jLabel69.setText("Remesh Sen");

        jLabel70.setBackground(new java.awt.Color(0, 102, 102));
        jLabel70.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel70.setForeground(new java.awt.Color(0, 51, 51));
        jLabel70.setText("Contact no. :-");

        jLabel71.setBackground(new java.awt.Color(0, 102, 102));
        jLabel71.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel71.setForeground(new java.awt.Color(0, 51, 51));
        jLabel71.setText("6874591023");

        jLabel72.setBackground(new java.awt.Color(0, 102, 102));
        jLabel72.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel72.setForeground(new java.awt.Color(0, 51, 51));
        jLabel72.setText("Address :-");

        jLabel73.setBackground(new java.awt.Color(0, 102, 102));
        jLabel73.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel73.setForeground(new java.awt.Color(0, 51, 51));
        jLabel73.setText("12 Shyam Nagar");

        jLabel74.setBackground(new java.awt.Color(0, 102, 102));
        jLabel74.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel74.setForeground(new java.awt.Color(0, 51, 51));
        jLabel74.setText("City :- ");

        jLabel75.setBackground(new java.awt.Color(0, 102, 102));
        jLabel75.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel75.setForeground(new java.awt.Color(0, 51, 51));
        jLabel75.setText("Ujjain");

        jLabel76.setBackground(new java.awt.Color(0, 102, 102));
        jLabel76.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel76.setForeground(new java.awt.Color(0, 51, 51));
        jLabel76.setText("State :-");

        jLabel77.setBackground(new java.awt.Color(0, 102, 102));
        jLabel77.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel77.setForeground(new java.awt.Color(0, 51, 51));
        jLabel77.setText("Madhya Pradesh");

        jLabel78.setBackground(new java.awt.Color(0, 102, 102));
        jLabel78.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel78.setForeground(new java.awt.Color(255, 51, 51));
        jLabel78.setText("Fee :-");

        jLabel79.setBackground(new java.awt.Color(0, 102, 102));
        jLabel79.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel79.setForeground(new java.awt.Color(0, 51, 51));
        jLabel79.setText("800.0 Rs ");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel68)
                                    .addComponent(jLabel70))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel9Layout.createSequentialGroup()
                                        .addComponent(jLabel71)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(jLabel69, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel72)
                                    .addComponent(jLabel74)
                                    .addComponent(jLabel76))
                                .addGap(55, 55, 55)
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel75)
                                    .addComponent(jLabel73)
                                    .addComponent(jLabel77)
                                    .addComponent(jLabel79))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addGap(106, 106, 106)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel78)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(jButton18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(jButton18, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel69)
                    .addComponent(jLabel68, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel70)
                    .addComponent(jLabel71))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel72)
                    .addComponent(jLabel73))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel74)
                    .addComponent(jLabel75))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel76)
                    .addComponent(jLabel77))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel78)
                    .addComponent(jLabel79))
                .addGap(9, 9, 9)
                .addComponent(jButton4))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(jLabel2)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        try {
            String query = "SELECT * FROM customer WHERE email =? and acc_Passowrd=? ";
            PreparedStatement ps = con.prepareStatement(query);
            ps.setString(1, login_id);
            ps.setString(2, passwor_d);
            System.out.print("start");
            ResultSet rs = ps.executeQuery();
            boolean bs = false;

            if (rs.next()) {
                bs = true;
                String firstName = rs.getString("Fname");
                System.out.println(firstName);
                String lastName = rs.getString("Lname");
                System.out.println(lastName);
                String address = rs.getString("address");
                String city = rs.getString("city");
                String state = rs.getString("state");
                CustName = firstName + " " + lastName;
                CustContactno = rs.getString("contact_no");
                CustAddress = address + " " + city + " " + state;
            }
        } catch (Exception e) {
            System.out.print("Exception 1 :" + e.getMessage());

        }
        
    
      
        try {
            
            
             String query = "SELECT * FROM appointment WHERE email =? and c_fullname=?  and c_contact_no=?";
            PreparedStatement ps = con.prepareStatement(query);
            ps.setString(1, data[0].E_mail());
            ps.setString(2, CustName);
            ps.setString(3, CustContactno);
        
            ResultSet rs = ps.executeQuery();
            boolean bs = false;

            if (rs.next()) {
                bs = true;
              JOptionPane.showMessageDialog(null,CustName +"  Appointment Already Booked ");
            }else{
                  ss_FullName = data[0].Fname() + " " + data[0].Lname();
        System.out.print(" name :" + ss_FullName);

        String Query = "Insert into appointment (s_fullname, serviceType, email, s_contact_no, s_address, city, state, pinCode, fee, c_fullname, c_contact_no, c_address) Values(?,?,?,?,?,?,?,?,?,?,?,?)";
     
             ps = con.prepareStatement(Query);
            System.out.print("Quary Executing   ");
            ps.setString(1, ss_FullName);
            ps.setString(2, data[0].Service_CAtagory());
            ps.setString(3, data[0].E_mail());
            ps.setString(4, data[0].Contact_no());
            ps.setString(5, data[0].Address());
            ps.setString(6, data[0].City());
            ps.setString(7, data[0].State());
            ps.setString(8, data[0].Pincode());
            ps.setString(9, data[0].fee());
            ps.setString(10, CustName);
            ps.setString(11, CustContactno);
            ps.setString(12, CustAddress);
            int result = ps.executeUpdate();
            System.out.print("excecuted  ");
            if (result > 0) {
                System.out.print("Done    ");
                JOptionPane.showMessageDialog(null, CustName + " !!!! Appointment Done !!! \n Name :" + ss_FullName + "\nService : " + data[0].Service_CAtagory()
                        + "\nContact No : " + data[0].Contact_no() + "\n Email Id : " + data[0].E_mail() + "\n Address : " + data[0].Address() + " , " + data[0].City()
                        + " , " + data[0].State() + "\nPincode : " + data[0].Pincode() + "\n Fees : " + data[0].fee());
            }
            }
        } catch (SQLException ex) {
            System.out.print("Error here :");
            Logger.getLogger(PlumberPage.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            String query = "SELECT * FROM customer WHERE email =? and acc_Passowrd=? ";
            PreparedStatement ps = con.prepareStatement(query);
            ps.setString(1, login_id);
            ps.setString(2, passwor_d);
            System.out.print("start");
            ResultSet rs = ps.executeQuery();
            boolean bs = false;

            if (rs.next()) {
                bs = true;
                String firstName = rs.getString("Fname");
                String lastName = rs.getString("Lname");
                String address = rs.getString("address");
                String city = rs.getString("city");
                String state = rs.getString("state");
                CustName = firstName + " " + lastName;
                CustContactno = rs.getString("contact_no");
                CustAddress = address + " " + city + " " + state;
            }
        } catch (Exception e) {
            System.out.print("Exception 1 :" + e.getMessage());

        }

   
      
        try {
            
              String query = "SELECT * FROM appointment WHERE email =? and c_fullname=?  and c_contact_no=?";
            PreparedStatement ps = con.prepareStatement(query);
            ps.setString(1, data[1].E_mail());
            ps.setString(2, CustName);
            ps.setString(3, CustContactno);
        
            ResultSet rs = ps.executeQuery();
            boolean bs = false;

            if (rs.next()) {
                bs = true;
              JOptionPane.showMessageDialog(null,CustName +"  Appointment Already Booked ");
            }else{
                  ss_FullName = data[1].Fname() + " " + data[1].Lname();
        System.out.print(" name :" + ss_FullName);

        String Query = "Insert into appointment (s_fullname, serviceType, email, s_contact_no, s_address, city, state, pinCode, fee, c_fullname, c_contact_no, c_address) Values(?,?,?,?,?,?,?,?,?,?,?,?)";

             ps = con.prepareStatement(Query);
            System.out.print("Quary Executing   ");
            ps.setString(1, ss_FullName);
            ps.setString(2, data[1].Service_CAtagory());
            ps.setString(3, data[1].E_mail());
            ps.setString(4, data[1].Contact_no());
            ps.setString(5, data[1].Address());
            ps.setString(6, data[1].City());
            ps.setString(7, data[1].State());
            ps.setString(8, data[1].Pincode());
            ps.setString(9, data[1].fee());
            ps.setString(10, CustName);
            ps.setString(11, CustContactno);
            ps.setString(12, CustAddress);
            int result = ps.executeUpdate();
            System.out.print("excecuted  ");
            if (result > 0) {
                System.out.print("Done    ");
                JOptionPane.showMessageDialog(null, CustName + " !!!! Appointment Done !!! \n Name :" + ss_FullName + "\nService : " + data[1].Service_CAtagory()
                        + "\nContact No : " + data[1].Contact_no() + "\n Email Id : " + data[1].E_mail() + "\n Address : " + data[1].Address() + " , " + data[1].City()
                        + " , " + data[1].State() + "\nPincode : " + data[1].Pincode() + "\n Fees : " + data[1].fee());
            }
            }
        } catch (SQLException ex) {
            System.out.print("Error here :");
            Logger.getLogger(PlumberPage.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            String query = "SELECT * FROM customer WHERE email =? and acc_Passowrd=? ";
            PreparedStatement ps = con.prepareStatement(query);
            ps.setString(1, login_id);
            ps.setString(2, passwor_d);
            System.out.print("start");
            ResultSet rs = ps.executeQuery();
            boolean bs = false;

            if (rs.next()) {
                bs = true;
                String firstName = rs.getString("Fname");
                String lastName = rs.getString("Lname");
                String address = rs.getString("address");
                String city = rs.getString("city");
                String state = rs.getString("state");
                CustName = firstName + " " + lastName;
                CustContactno = rs.getString("contact_no");
                CustAddress = address + " " + city + " " + state;

                System.out.println(CustName);
                System.out.println(CustContactno);
                System.out.println(CustAddress);
            }
        } catch (Exception e) {
            System.out.print("Exception 1 :" + e.getMessage());

        }
        
    
      
        try {
            
              String query = "SELECT * FROM appointment WHERE email =? and c_fullname=?  and c_contact_no=?";
            PreparedStatement ps = con.prepareStatement(query);
            ps.setString(1, data[2].E_mail());
            ps.setString(2, CustName);
            ps.setString(3, CustContactno);
        
            ResultSet rs = ps.executeQuery();
            boolean bs = false;

            if (rs.next()) {
                bs = true;
              JOptionPane.showMessageDialog(null,CustName +"  Appointment Already Booked ");
            }else{
                  ss_FullName = data[2].Fname() + " " + data[2].Lname();
        System.out.print(" name :" + ss_FullName);

        String Query = "Insert into appointment (s_fullname, serviceType, email, s_contact_no, s_address, city, state, pinCode, fee, c_fullname, c_contact_no, c_address) Values(?,?,?,?,?,?,?,?,?,?,?,?)";
       
             ps = con.prepareStatement(Query);
            System.out.print("Quary Executing   ");
            ps.setString(1, ss_FullName);
            ps.setString(2, data[2].Service_CAtagory());
            ps.setString(4, data[2].Contact_no());
            ps.setString(3, data[2].E_mail());
            ps.setString(5, data[2].Address());
            ps.setString(6, data[2].City());
            ps.setString(7, data[2].State());
            ps.setString(8, data[2].Pincode());
            ps.setString(9, data[2].fee());
            ps.setString(10, CustName);
            ps.setString(11, CustContactno);
            ps.setString(12, CustAddress);
            int result = ps.executeUpdate();
            System.out.print("excecuted  ");
            if (result > 0) {
                System.out.print("Done    ");
                JOptionPane.showMessageDialog(null, CustName + " !!!! Appointment Done !!! \n Name :" + ss_FullName + "\nService : " + data[2].Service_CAtagory()
                        + "\nContact No : " + data[2].Contact_no() + "\n Email Id : " + data[2].E_mail() + "\n Address : " + data[2].Address() + " , " + data[2].City()
                        + " , " + data[2].State() + "\nPincode : " + data[2].Pincode() + "\n Fees : " + data[2].fee());
            }
            }
        } catch (SQLException ex) {
            System.out.print("Error here :");
//            Logger.getLogger(PlumberPage.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try {
            String query = "SELECT * FROM customer WHERE email =? and acc_Passowrd=? ";
            PreparedStatement ps = con.prepareStatement(query);
            ps.setString(1, login_id);
            ps.setString(2, passwor_d);
            System.out.print("start");
            ResultSet rs = ps.executeQuery();
            boolean bs = false;

            if (rs.next()) {
                bs = true;
                String firstName = rs.getString("Fname");
                String lastName = rs.getString("Lname");
                String address = rs.getString("address");
                String city = rs.getString("city");
                String state = rs.getString("state");
                CustName = firstName + " " + lastName;
                CustContactno = rs.getString("contact_no");
                CustAddress = address + " " + city + " " + state;

                System.out.println(CustName);
                System.out.println(CustContactno);
                System.out.println(CustAddress);
            }
        } catch (Exception e) {
            System.out.print("Exception 1 :" + e.getMessage());

        }
        
        
      
        try {
            
              String query = "SELECT * FROM appointment WHERE email =? and c_fullname=?  and c_contact_no=?";
            PreparedStatement ps = con.prepareStatement(query);
            ps.setString(1, data[3].E_mail());
            ps.setString(2, CustName);
            ps.setString(3, CustContactno);
        
            ResultSet rs = ps.executeQuery();
            boolean bs = false;

            if (rs.next()) {
                bs = true;
              JOptionPane.showMessageDialog(null,CustName +"  Appointment Already Booked ");
            }
            else{
                  ss_FullName = data[3].Fname() + " " + data[3].Lname();
        System.out.print(" name :" + ss_FullName);

        String Query = "Insert into appointment (s_fullname, serviceType, email, s_contact_no, s_address, city, state, pinCode, fee, c_fullname, c_contact_no, c_address) Values(?,?,?,?,?,?,?,?,?,?,?,?)";
     
             ps = con.prepareStatement(Query);
            System.out.print("Quary Executing   ");
            ps.setString(1, ss_FullName);
            ps.setString(2, data[3].Service_CAtagory());
            ps.setString(4, data[3].Contact_no());
            ps.setString(3, data[3].E_mail());
            ps.setString(5, data[3].Address());
            ps.setString(6, data[3].City());
            ps.setString(7, data[3].State());
            ps.setString(8, data[3].Pincode());
            ps.setString(9, data[3].fee());
            ps.setString(10, CustName);
            ps.setString(11, CustContactno);
            ps.setString(12, CustAddress);
            int result = ps.executeUpdate();
            System.out.print("excecuted  ");
            if (result > 0) {
                System.out.print("Done    ");
                JOptionPane.showMessageDialog(null, CustName + " !!!! Appointment Done !!! \n Name :" + ss_FullName + "\nService : " + data[3].Service_CAtagory()
                        + "\nContact No : " + data[3].Contact_no() + "\n Email Id : " + data[3].E_mail() + "\n Address : " + data[3].Address() + " , " + data[3].City()
                        + " , " + data[3].State() + "\nPincode : " + data[3].Pincode() + "\n Fees : " + data[3].fee());
            }
            }
        } catch (SQLException ex) {
            System.out.print("Error here :");
//            Logger.getLogger(PlumberPage.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton12ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws Exception {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
//              //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new AmbulancePage().setVisible(true);
//            }
//        });
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new AmbulancePage().setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    // End of variables declaration//GEN-END:variables
}
